baseURL = "https://dearruda.me"
copyright = "This work is licensed under a Creative Commons Attribution-NonCommercial 4.0 International License."
defaultContentLanguage = "en"
enableEmoji = true
googleAnalytics = "UA-129215154-4"
languageCode = "en-us"
pygmentsCodefences = true
pygmentsUseClasses = true
rssLimit = 10
theme = "hermit"
title = "Ricardo de Arruda"
[author]
name = "Ricardo de Arruda"
[blackfriday]
[menu]
[params]
Iam = "I'm a"
IamList = ["Full Stack Dev", "VIM fanboy", "minimalist", "Linux Fanboy", "pythoneer 🐍"]
dateform = "Jan 2, 2006"
dateformNum = "2006-01-02"
dateformNumTime = "2006-01-02 15:04 -0700"
dateformShort = "Jan 2"
description = "Ricardo de Arruda personal webpage."
footerCopyright = " &#183; <a href=\"https://creativecommons.org/licenses/by-nc/4.0/\" target=\"_blank\" rel=\"noopener\">CC BY-NC 4.0</a>"
justifyContent = false
themeColor = "#494f5c"
[[params.social]]
name = "Dev.to"
url = "https://dev.to/arrudaricardo/"
[[params.social]]
name = "LinkedIn"
url = "https://www.linkedin.com/in/ricardo-arruda-508b918b"
[[params.social]]
name = "instagram"
url = "https://www.instagram.com/ricarruda7/"
[[params.social]]
name = "github"
url = "https://github.com/arrudaricardo/"
[[params.social]]
name = "email"
url = "mailto:settiricardo@gmail.com?subject=Hey%20Ricardo.&body="
[[params.social]]
name = "cv"
url = "resume"
[taxonomies]
category = ""
tag = "tags"
